### ISSUE TITLE
Refreshing tokens does not seem to refresh refresh_token

### ISSUE THREAD

**Issue by AxelTheGerman** [beezwax/aws-cognito-srp-ruby#4]
Hi,

Thanks so much for this great library, makes working with Cognito auth so much easier.

However, I seem to be unable to refresh the `refresh_token`.

```
      aws_srp = Aws::CognitoSrp.new(
        username: '',
        password: '',
        pool_id: COGNITO_USER_POOL_ID,
        client_id: COGNITO_CLIENT_ID,
        client_secret: COGNITO_CLIENT_SECRET,
        aws_client: Aws::CognitoIdentityProvider::Client.new(region: COGNITO_USER_POOL_REGION)
      )
      auth_response = aws_srp.refresh_tokens(refresh_token, user_id_for_srp:)
```

The above snippet does successfully get me a new `access_token`, but the `refresh_token` stays the same - I believe it's actually `nil` from the `auth_response`.

I believe this gem is following what the docs say about getting a new refresh token but I was wondering if someone else has similar issues (or doesn't) - https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-the-refresh-token.html

Thanks so much!

**Comment by pilaf** [comment]
Hi @AxelTheGerman 

> The above snippet does successfully get me a new `access_token`, but the `refresh_token` stays the same - I believe it's actually `nil` from the `auth_response`.
>
> I believe this gem is following what the docs say about getting a new refresh token but I was wondering if someone else has similar issues (or doesn't) - https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-the-refresh-token.html

If I'm not mistaken when you request new tokens using the refresh tokens API you only get new ID and access tokens, but no new refresh token. The previous refresh token should still be valid after use and will expire naturally after 30 days.

Please let me know if I misunderstood the issue, otherwise I will close this.

**Comment by AxelTheGerman** [comment]
You might be right!

> The previous refresh token should still be valid after use and will expire naturally after 30 days.

This is quite unfortunate however as it means users have to log in every <30 days.

Luckily I no longer need to use this integration and the one I'm using instead has different auth flows that do keep users logged in.
